apiVersion: 1

datasources:
  - name: Manufacturing CSV
    type: marcusolsson-csv-datasource
    access: proxy
    orgId: 1
    isDefault: true
    jsonData:
      storage: file
    secureJsonData:
      path: /var/lib/grafana/csv
    editable: true